[env]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 9600

lib_deps =
  majicDesigns/MD_Parola
  majicDesigns/MD_MAX72XX

extra_scripts =
  pre:scripts/generate_version_header.py
  pre:scripts/embed_setup_html.py

[env:esp32dev]

[env:wokwi]
build_flags =
  -D WOKWI_SIM=1
