[wokwi]
version = 1
firmware = ".pio/build/wokwi/firmware.bin"
elf = ".pio/build/wokwi/firmware.elf"
rfc2217ServerPort = 4000

[gdb]
enabled = false

[[net.forward]]
from = "localhost:8180"
to = "target:80"
