#!/usr/bin/env python3
"""Convert 32-pixel-wide source artwork into firmware bitmap data."""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError as exc:
    raise SystemExit(
        "Pillow is required to import pixel art. Install it with: python3 -m pip install Pillow"
    ) from exc


ART_WIDTH = 32
BRIGHTNESS_THRESHOLD = 127.5
IMAGE_EXTENSIONS = {".bmp", ".gif", ".jpg", ".jpeg", ".png", ".webp"}

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "pixel-art"
OUTPUT_DIR = ROOT / "Firmware-PIO" / "src" / "programs" / "pixel_art" / "generated"


def natural_key(path: Path) -> list[object]:
    return [
        int(part) if part.isdigit() else part.lower()
        for part in re.split(r"(\d+)", path.name)
    ]


def symbol_name(path: Path, used: set[str]) -> str:
    symbol = re.sub(r"[^A-Za-z0-9_]+", "_", path.stem).strip("_").lower()
    if not symbol:
        symbol = "art"
    if symbol[0].isdigit():
        symbol = f"art_{symbol}"

    candidate = symbol
    suffix = 2
    while candidate in used:
        candidate = f"{symbol}_{suffix}"
        suffix += 1
    used.add(candidate)
    return candidate


def source_images() -> list[Path]:
    if not SOURCE_DIR.exists():
        return []
    return sorted(
        (
            path
            for path in SOURCE_DIR.iterdir()
            if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
        ),
        key=natural_key,
    )


def alpha_composited_luminance(pixel: tuple[int, ...]) -> float:
    red, green, blue = pixel[:3]
    alpha = pixel[3] / 255.0 if len(pixel) >= 4 else 1.0
    red *= alpha
    green *= alpha
    blue *= alpha
    return 0.2126 * red + 0.7152 * green + 0.0722 * blue


def packed_rows(path: Path) -> list[int]:
    with Image.open(path) as image:
        rgba = image.convert("RGBA")
        if rgba.width != ART_WIDTH:
            raise ValueError(f"{path}: expected width {ART_WIDTH}, got {rgba.width}")
        if rgba.height <= 0:
            raise ValueError(f"{path}: image height must be positive")

        rows: list[int] = []
        pixels = rgba.load()
        for y in range(rgba.height):
            row = 0
            for x in range(ART_WIDTH):
                if alpha_composited_luminance(pixels[x, y]) <= BRIGHTNESS_THRESHOLD:
                    row |= 1 << (ART_WIDTH - 1 - x)
            rows.append(row)
        return rows


def write_art_header(path: Path, symbol: str, rows: list[int]) -> str:
    header_path = OUTPUT_DIR / f"{symbol}.h"
    array_name = f"{symbol.upper()}_ROWS"
    display_name = path.stem

    lines = [
        "// Auto-generated by scripts/import-pixel-art.py - do not edit",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        "",
        "namespace PixelArt {",
        f"constexpr const char {symbol.upper()}_NAME[] = \"{display_name}\";",
        f"constexpr uint16_t {symbol.upper()}_HEIGHT = {len(rows)};",
        f"const uint32_t {array_name}[] PROGMEM = {{",
    ]
    for row in rows:
        lines.append(f"    0x{row:08X}UL,")
    lines.extend(
        [
            "};",
            "",
            "} // namespace PixelArt",
            "",
        ]
    )

    header_path.write_text("\n".join(lines), encoding="utf-8")
    return array_name


def write_catalog(entries: list[tuple[str, str]]) -> None:
    catalog_h = OUTPUT_DIR / "pixel_art_catalog.h"
    catalog_cpp = OUTPUT_DIR / "pixel_art_catalog.cpp"

    catalog_h.write_text(
        "\n".join(
            [
                "// Auto-generated by scripts/import-pixel-art.py - do not edit",
                "#pragma once",
                "",
                "#include <stddef.h>",
                "#include <stdint.h>",
                "",
                "namespace PixelArt {",
                "",
                "struct Image {",
                "  const char *name;",
                "  uint16_t height;",
                "  const uint32_t *rows;",
                "};",
                "",
                "extern const Image *const IMAGES;",
                "extern const size_t IMAGE_COUNT;",
                "",
                "} // namespace PixelArt",
                "",
            ]
        ),
        encoding="utf-8",
    )

    lines = [
        "// Auto-generated by scripts/import-pixel-art.py - do not edit",
        '#include "pixel_art_catalog.h"',
        "",
    ]
    for symbol, _ in entries:
        lines.append(f'#include "{symbol}.h"')
    lines.extend(["", "namespace PixelArt {", ""])

    if entries:
        lines.append("namespace {")
        lines.append("const Image IMAGE_LIST[] = {")
        for symbol, array_name in entries:
            upper = symbol.upper()
            lines.append(f"    {{{upper}_NAME, {upper}_HEIGHT, {array_name}}},")
        lines.append("};")
        lines.append("} // namespace")
        lines.append("")
        lines.append("const Image *const IMAGES = IMAGE_LIST;")
        lines.append("const size_t IMAGE_COUNT = sizeof(IMAGE_LIST) / sizeof(IMAGE_LIST[0]);")
    else:
        lines.append("const Image *const IMAGES = nullptr;")
        lines.append("const size_t IMAGE_COUNT = 0;")

    lines.extend(["", "} // namespace PixelArt", ""])
    catalog_cpp.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    images = source_images()
    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    used_symbols: set[str] = set()
    entries: list[tuple[str, str]] = []
    for image_path in images:
        symbol = symbol_name(image_path, used_symbols)
        rows = packed_rows(image_path)
        array_name = write_art_header(image_path, symbol, rows)
        entries.append((symbol, array_name))

    write_catalog(entries)
    print(f"Imported {len(entries)} pixel art image(s) into {OUTPUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
